app = 'ollama-byrdson'
primary_region = 'ord'

[build]
  image = 'ollama/ollama'

[[mounts]]
  source = 'ollama_byrdson_models'
  destination = '/root/.ollama'
  initial_size = '5gb'

[http_service]
  internal_port = 11434
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'l40s'