name: Deploy to fly.io
on:
#  push:
#    branches:
#      - main
#    paths:
#      - fly.toml
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
        
      - name: Deploy to fly.io
        run: flyctl deploy --detach
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}